### PR TITLE
Separate Node to Success/Failure objects

### PR DESCRIPTION
**Pull request by minamorl**
@wavebeem #10 is Mostly done. The rest is error messages. Would you mind helping me?

### CODE REVIEW

**Comment by minamorl** [comment]
I merge this PR for now.

**Comment by wavebeem** [comment]
Suggestion: snake_case method names

https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables

**Comment by minamorl** [comment]
ok, will fix it.

**Comment by minamorl** [comment]
I fixed it :)

**Comment by wavebeem** [comment]
Yay

**Pull request merged**
